name: dxvk-async

on:
  push:
    paths: .github/workflows/dxvk-async.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DXVK_ASYNC: 1
      VERSION: 1.10.2
    steps:

    - name: Checkout
      uses: actions/checkout@v3.0.2
      with:
        repository: Sporif/dxvk-async

    - name: Checkout
      uses: actions/checkout@v3.0.2
      with:
        repository: doitsujin/dxvk
        ref: v${{ env.VERSION }}
        clean: false

    - name: Apply patches
      run: |
        git apply dxvk-async-af418dc.patch

    - name: Build release
      id: build-release
      uses: Joshua-Ashton/arch-mingw-github-action@v7
      with:
        command: |
          export VERSION_NAME="${GITHUB_REF##*/}-${GITHUB_SHA##*/}"
          ./package-release.sh ${VERSION_NAME} build --no-package
          echo "VERSION_NAME=${VERSION_NAME}" >> $GITHUB_ENV

    - name: Upload artifacts
      id: upload-artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        name: dxvk-${{ env.VERSION }}
        path: build/dxvk-${{ env.VERSION_NAME }}
        if-no-files-found: error
